### ISSUE TITLE
ZSTD-compress kernel modules support?

### ISSUE THREAD

**Issue by xuanruiqi** [dracutdevs/dracut#945] opened 2020-10-15 07:34 UTC
**Describe the bug**
Recently I tried to move to ZSTD for kernel compression, but it seems that Dracut is not very happy. It claims that it "can't find" the desired modules in the compressed `.ko.zst` files.

**Distribution used**
Arch Linux

**Dracut version**
050

**Init system**
systemd

**To Reproduce**

    dracut -v -f --no-hostonly-cmdline /boot/initramfs-xanmod.img --kver 5.8.15-xanmod1-1

**Expected behavior**
Dracut finds all required modules and builds them into the initramfs.

**Comment by xuanruiqi** [comment] 2020-10-15 07:39
Rebuilding the kernel with XZ module compression does work, so I suppose it's a ZSTD support problem.

**Comment by xuanruiqi** [comment] 2020-10-15 07:40
This might not be a bug, more of documentation/feature...

**Comment by danimo** [comment] 2020-10-16 12:35
Good idea indeed. Can you test the patch in the referenced PR?

**Comment by xuanruiqi** [comment] 2020-10-16 14:37
Thanks; it would take some time (I'd have to build the PR'd dracut and rebuild my kernel with ZSTD-compressed modules). But I'd love to try it out!

**Comment by xuanruiqi** [comment] 2020-10-16 17:30
Not working: it seems you've been hardcoding the extensions in the file, but `.zst` is more frequently used as an extension for ZSTD-compressed files (and kernel modules) than `.zstd`.

**Comment by xuanruiqi** [comment] 2020-10-16 17:39
OK, the issue seems beyond that... I hand-patched the code to add the extension `.zst` and it was still not working.

**Comment by danimo** [comment] 2020-10-16 19:39
I have updated the patch. This works for me.

**Comment by xuanruiqi** [comment] 2020-10-20 07:00
Haven't had the chance to try again, let me try...

**Comment by xuanruiqi** [comment] 2020-10-29 22:15
Still not working for me:

    dracut-install: Failed to find module 'pinctrl_amd' /lib/modules/5.9.2-xanmod1-1//kernel/drivers/pinctrl/pinctrl-amd.ko.zst
    dracut-install: Failed to find module 'usbhid' /lib/modules/5.9.2-xanmod1-1//kernel/drivers/hid/usbhid/usbhid.ko.zst
    dracut-install: Failed to find module 'hid_generic' /lib/modules/5.9.2-xanmod1-1//kernel/drivers/hid/hid-generic.ko.zst
    dracut-install: Failed to find module 'hid_lg_g15' /lib/modules/5.9.2-xanmod1-1//kernel/drivers/hid/hid-lg-g15.ko.zst
    dracut-install: Failed to find module 'hid_logitech_dj' /lib/modules/5.9.2-xanmod1-1//kernel/drivers/hid/hid-logitech-dj.ko.zst
    dracut-install: Failed to find module 'hid_logitech_hidpp' /lib/modules/5.9.2-xanmod1-1//kernel/drivers/hid/hid-logitech-hidpp.ko.zst
    dracut-install: Failed to find module 'hid_logitech' /lib/modules/5.9.2-xanmod1-1//kernel/drivers/hid/hid-logitech.ko.zst

**Comment by danimo** [comment] 2020-11-26 14:44
@xuanruiqi which kernel starts to support zstd btw?

**Comment by xuanruiqi** [comment] 2020-11-26 14:46
You need to have a patched kernel; it isn't in the mainline yet. Xanmod for example provides this patch.

**Comment by xuanruiqi** [comment] 2020-12-26 18:33
This is not stale as AFAIK it is not fixed yet

**Comment by Atemu** [comment] 2020-12-27 09:47
Are you sure it supports zstd-compressed *modules*? The mainline kernel supports zstd for the kernel image and initrd but not for modules for example.

**Comment by xuanruiqi** [comment] 2020-12-29 07:00
Yes, at least Xanmod supports it. AFAIK, probably a few patchsets do. Since dracut was supporting ZSTD-compressed kernel images way before it went official, it might be a good idea to support this ahead of mainline.

**Comment by sirlucjan** [comment] 2021-01-08 17:08
As much as possible you can use modules compressed in .zst format - I use such a solution myself, but using patched mkinitcpio. The problem is probably kmod - only yesterday released version 28 allows you to handle modules compressed in zstd format without any problems. Use the new kmod and it should work.

**Comment by xuanruiqi** [comment] 2021-01-21 23:44
Since @danimo's fix cannot break existing features, I would really appreciate if this could get merged soon! And then I could see if with the latest `kmod` I could get everything to work...

**Comment by johannbg** [comment] 2021-02-24 05:03
This seems to have been resolved with the 28 release of kmod hence closing.

**Closed by johannbg** 2021-02-24 05:03 UTC
Labels: bug
