### ISSUE TITLE
fsfreeze can cause problems on Btrfs

### ISSUE THREAD

**Issue by cmurf** [dracutdevs/dracut#398] opened 2018-04-28 08:12 UTC
```
$ grep -n fsfreeze /usr/bin/dracut
1840:# use fsfreeze only if we're not writing to /
1842:    if ! $(fsfreeze -f $(dirname "$outfile") 2>/dev/null && fsfreeze -u $(dirname "$outfile") 2>/dev/null); then
1843:        dinfo "dracut: warning: could not fsfreeze $(dirname "$outfile")"
[chris@f28s ~]$ 
```

When there is a boot subvolume, and fstab uses mount option subvol=boot to mount at /boot, the above check still allows fsfreeze to happen on the entire Btrfs volume which includes /

If I also decide to do something a bit nutty:

`sudo strace -s 60 -ff -o stracednfinstallkernel.out dnf install -y ~/kernelrpms` where the destination for the 7000+ files this writes out is root fs. This never completes. The fsfreeze -f is issued and it never finishes (why it doesn't finish is uncertain and might be a kernel bug, it'll take more testing). Also the resulting file system is not bootable by default, the freeze starts before grubby has added the initrd line, so the default GRUB entry isn't bootable. (At least on Fedora which uses grubby.)

Anyway, so far in my testing sync() is sufficient on all file systems to successfully flush boot related files as far as the bootloader is concerned, *except* XFS.

**Comment by cmurf** [comment] 2018-04-28 08:54
sysrq+t issued during the hung freeze
[journal.log](https://github.com/dracutdevs/dracut/files/1957496/journal.log)

**Comment by cmurf** [comment] 2018-04-29 21:58
I can reproduce this on XFS by making /boot a directory on rootfs; and then modifying dracut do always `fsfreeze -f /boot && fsfreeze -u /boot`

I think this method of working around XFS behaving differently than FAT, ext4, and Btrfs when sync() is called means it should be reverted until the fs devs sort this out. Either XFS devs need sync() to work the same as other file systems; or fsdevs need a new atomic FIFREEZE+FITHAW ioctl. Obviously all /boot related changes care to have fully committed for bootloader purposes is kernel, initramfs, and the bootloader config files, not literally everything on the file system.

The previous dracut behavior used sync on the initramfs file, which sync.c in turn translates into fsync(). So I'm suggesting dracut use only sync, no options and no file specified. That will call sync() which other than XFS, so far in my testing commits files such that the bootloader sees the changes.

**Comment by fcami** [comment] 2018-04-29 22:28
I'll open a PR so that we don't do anything for btrfs and be done with it.
Using fsfreeze -f then -u is the right thing to do when /boot is hosted on a journaled filesystem especially on xfs.

**Comment by cmurf** [comment] 2018-04-30 04:51
It's possible the strace being the parent of all child processes is what causes the hang. When I use strace -D flag, the problem doesn't happen.

**Comment by fcami** [comment] 2018-04-30 09:19
Given the install base using xfs on /boot this is an issue that needs a fix.

**Comment by kyle-walker** [comment] 2018-04-30 12:30
+1 For omitting BTRFS and keeping the freeze/unfreeze for other filesystems.

Until we can get some sort of legitimate filesystem API around syncing journal/log contents to disk, a freeze/unfreeze seems like the way to go.

**Comment by mwilck** [comment] 2020-01-29 16:17
This problem still persists. It has the effect that on a standard SUSE installation, writing an initrd to `/tmp` (for testing purposes, say) freezes the entire system.

**Comment by mwilck** [comment] 2020-01-30 10:31
I proposed a patch for btrfs in #713. I still don't quite grok why fsfreeze is necessary at all and a simpe sync wouldn't be enough.

**Comment by fcami** [comment] 2020-01-30 10:36
sync flushes the buffers which, on xfs, commits changes to the log only. grub does not read the log. fsfreeze makes sure the log changes are committed to the file system.

**Comment by mwilck** [comment] 2020-01-30 10:54
> sync flushes the buffers which, on xfs, commits changes to the log only.

Thanks for the explanation. Is there any evidence that other filesystems need this, too? If not, the simple alternative to my patch would be to fsfreeze on xfs only, as proposed earlier.

**Comment by fcami** [comment] 2020-01-30 11:15
According to ext* file systems developers, only ext2 is 100% immune as it is not journalled. Therefore a simple sync would suffice on ext2.
All journalled file systems should exhibit the issue, but anecdotal testing seems to point out that xfs delays log=>fs writes more than ext3/4, making reproducing the issue trivial. Still, ext3 and ext4 need fsfreeze.

**Comment by mwilck** [comment] 2020-01-30 11:26
@fcami, fine then, please review #713. I suppose btrfs would be susceptible to the same issue as ext3/4, yet we need to avoid that system freeze, too.

**Comment by mwilck** [comment] 2020-02-11 10:57
@facmi, please have a look at https://github.com/dracutdevs/dracut/pull/713#issuecomment-584578974.

**Closed** 2020-03-06 10:37 UTC

**Comment by ddiss** [comment] 2020-09-07 09:38
> Using fsfreeze -f then -u is the right thing to do when /boot is hosted on a journaled filesystem especially on xfs.
> sync flushes the buffers which, on xfs, commits changes to the log only. grub does not read the log. fsfreeze makes sure the log changes are committed to the file system.

@fcami Where did you get this information from? Dracut is calling `sync "$outfile"`, which results in an fsync() syscall. The fsync() semantics are documented in the FSYNC(2) man page:
```
       fsync()  transfers  ("flushes")  all  modified  in-core data of (i.e., modified buffer cache pages for) the file referred to by the file descriptor fd to the disk
       device (or other permanent storage device) so that all changed information can be retrieved even if the system crashes or  is  rebooted.   This  includes  writing
       through or flushing a disk cache if present.  The call blocks until the device reports that the transfer has completed.
```

IMO there is absolutely no reason to freeze *all I/O* to the output filesystem, regardless of whether the filesystem is journaled, COW or any other type.

**Comment by fcami** [comment] 2020-09-07 09:47
@ddis the key point is that:
- fsync will make sure the filesystem (data+journal) is consistent ; if an unclean shutdown is done, the FS will recover when it's mounted.
 but
- GRUB/GRUB2 will not read the journal, only the data.

**Comment by ddiss** [comment] 2020-09-07 09:48
> > Using fsfreeze -f then -u is the right thing to do when /boot is hosted on a journaled filesystem especially on xfs.
> > sync flushes the buffers which, on xfs, commits changes to the log only. grub does not read the log. fsfreeze makes sure the log changes are committed to the file system.

> @fcami Where did you get this information from? Dracut is calling sync "$outfile", which results in an fsync() syscall. The fsync() semantics are documented in the FSYNC(2) man page:

Bleh, I should read the full text that I'm quoting before commenting, sorry.
The keyword here is **GRUB** - https://github.com/ostreedev/ostree/commit/8642ef5ab3fec3ac8eb8f193054852f83a8bc4d0 - so the fsfreeze is a workaround for GRUB's broken XFS support.
I still think that the correct fix here belongs in GRUB.

**Comment by fcami** [comment] 2020-09-07 09:52
@ddis or just don't use a journaled file system for /boot...

**Comment by ddiss** [comment] 2020-09-07 10:14
@fcami are you sure that GRUB's ext4 support is also affected by this bug? It'd be good to make the Dracut workaround behaviour FS dependent - on my system I see a ~100ms delay added with freeze/thaw, which adds up given how frequently my initramfs is rebuilt.

**Comment by fcami** [comment] 2020-09-07 10:26
@ddiss IIRC:
- The "sync (much) later" behavior of XFS makes the issue more likely
- I could reproduce the issue with ext4 too at the time this was discussed by simulating a power cut after installing a new kernel. 
Whether that changed between then and now, I don't know.

**Comment by ddiss** [comment] 2020-09-07 11:36
> * The "sync (much) later" behavior of XFS makes the issue more likely
> * I could reproduce the issue with ext4 too at the time this was discussed by simulating a power cut after installing a new kernel.
    Whether that changed between then and now, I don't know.

Thanks. I'll work on a change to make the freeze/thaw more FS dependent, extending on the existing "msdos" exception.

**Comment by ddiss** [comment] 2020-09-07 12:25
Further reference: https://patchwork.kernel.org/patch/9732257/#20485567

Ideally the freeze/thaw workaround would only be invoked if all of the following conditions are true:
1. Bootloader has broken support for some filesystems (E.g. GRUB)
2. initramfs resides on a filesystem which is broken for the bootloader (e.g. XFS, ext4, ext3(?), BTRFS(?))
3. filesystem can be put in a state that's acceptable for the bootloader by invoking freeze/thaw (e.g. XFS, ext4(?), ...)

Checking from Dracut which bootloader is used for (1) would be a little ugly/difficult, so it's probably better to assume that the condition is always true. Determining the FS list for (2) would require audit / test of bootloader filesystem support. Determining the FS list for (3) would require audit / test of Linux filesystems.

**Comment by mwilck** [comment] 2020-09-07 15:04
> @ddis or just don't use a journaled file system for /boot...

I'm not sure I follow. With non-journaled file systems, it's *harder* to recover from crash or power loss.

True, on ext2, data will be clean after the `fsync()`. OTOH, `fsync()` may take longer to complete, and if the system crashes before it's finished, you'd be at least as hosed as you are with a journalling FS. What am I missing?

**Comment by fcami** [comment] 2020-09-07 15:18
@mwilck 
- there is no journal to read - so from GRUB's PoV it's simpler
- if all you write to /boot is an updated config file, a vmlinuz and an initramfs, it only takes 3-4 fsync calls to be clean so the time window during which a crash can be problematic is extremely short.
- fsync() on xfs/ext4 does not guarantee the system can reboot, only fsfreeze does that.

**Comment by ddiss** [comment] 2020-09-07 15:38
> fsync() on xfs/ext4 does not guarantee the system can reboot after a crash, only fsfreeze does that.

Well... successful fsync() on xfs/ext4 does guarantee that the file has reached persistent storage. The problem is that GRUB doesn't fully support the xfs/ext4 on-disk format so it may fail to boot without the freeze/thaw force-log-flush workaround.

**Comment by fcami** [comment] 2020-09-07 15:43
@ddis exactly that, yes.

**Comment by cmurf** [comment] 2020-09-07 23:54
I doubt bootloaders will do journal replay, it's already complicated code in the kernel. And the fs devs find the idea of having various implementations in bootloaders, each aging differently, kinda hilarious.

If we're using drop-in bootloader configuration files, like BootLoaderSpec; then it should be true kernel update ends with the bootloader config being written and the file system sync'd. If a crash happens before sync completes, the old config still applies and still boots the previous kernel. If the update regime depends on writing new files, and renameat(2) to replace, while this is atomic in the VFS there is a small window where things become ambiguous. I expect similar on ext2 (or ext3/4 with the journal disabled. If the file system needs fsck, it's uncertain if the bootloader can properly read the file system and boot.

Curiously, there might be a role for btrfs to help out. Btrfs doesn't have a conventional journal. It has a tree log for fsync optimization, but skipping the replay on it (if the bootloader doesn't know how to do it) should just reveal the previous valid kernel rather than some in between state. Another possibility is to just always mount a btrfs $BOOT using notreelog which turns fsync() into a full sync(). It's a bit slower to commit, but if there's a crash, the boot state is unambigous.
