### ISSUE TITLE
dracut doesn't generate initramfs with bash 4.4

### ISSUE THREAD

**Issue by ghost** [dracutdevs/dracut#155] opened 2016-10-01 13:29 UTC
I've tried generating initramfs with the latest dracut and bash 4.4. The command I use is:
"dracut --debug -v -f -L 3 /boot/initramfs 4.7.6"

but the dracut debug mode hangs with this message:

/usr/lib/dracut/dracut-init.sh@955(instmods): local _optional=-o
/usr/lib/dracut/dracut-init.sh@956(instmods): local _silent
/usr/lib/dracut/dracut-init.sh@957(instmods): local _ret
/usr/lib/dracut/dracut-init.sh@959(instmods): [[ '' = yes ]]
/usr/lib/dracut/dracut-init.sh@961(instmods): [[ '' = -\c ]]
/usr/lib/dracut/dracut-init.sh@965(instmods): [[ '' = -\s ]]
/usr/lib/dracut/dracut-init.sh@970(instmods): (( 0 == 0 ))
/usr/lib/dracut/dracut-init.sh@971(instmods): read -r -d '' -a args

I believe that maybe the "read -r -d '' -a args"[1] is waiting for stdin and this is why dracut hangs.
1. https://github.com/dracutdevs/dracut/blob/master/dracut-init.sh#L971

**Comment by haraldh** [comment] 2016-10-10 09:57
Please add more debug context. Which dracut module is calling instmods?

**Comment by gnurama** [comment] 2016-10-11 17:51
I want to point out that the issue is only inside a chroot environment. When generating 'no hostonly' initramfs inside the chroot environment, ie with -N option, dracut doesn't hang at all. Here is the entire debug output:

https://paste.ee/p/aOFDp

**Comment by haraldh** [comment] 2016-10-12 09:31
Did you bind mount /proc /sys /dev /run in the chroot?

**Comment by gnurama** [comment] 2016-10-12 16:03
Yes I did, using 'mount -o bind' command.

**Comment by danimo** [comment] 2016-11-07 16:02
This is a duplicate of #118.

**Comment by danimo** [comment] 2019-05-08 11:20
This can be closed.

**Closed** 2020-08-07 13:09 UTC
