### ISSUE TITLE
70-uaccess.rules seems to require /lib64/elogind/elogind-uaccess-command

### ISSUE THREAD

**Issue by amano-kenji** [dracutdevs/dracut#1909] opened 2022-08-15 00:51 UTC
**Describe the bug**

initramfs tries to execute /lib64/elogind/elogind-uaccess-command multiple times.
It seems 70-uaccess.rules requires /lib64/elogind/elogind-uaccess-command

Adding
```
install_items+=" /lib64/elogind/elogind-uaccess-command "
```
to /etc/dracut.conf works around the issue.

**Distribution used**

Gentoo Linux

**Dracut version**

057

**Init system**

OpenRC

**Comment by pvalena** [comment] 2022-08-31 11:43
Can you post a log / reproducer?

**Comment by amano-kenji** [comment] 2022-09-01 12:20
How can I do that?

**Comment by amano-kenji** [comment] 2022-11-30 12:40
[70-uaccess.rules.txt](https://github.com/dracutdevs/dracut/files/10123209/70-uaccess.rules.txt)

Here.

**Comment by LaszloGombos** [comment] 2022-11-30 15:20
> It seems 70-uaccess.rules requires /lib64/elogind/elogind-uaccess-command

@amano-kenji  Thanks for the file, but this file does not seem to have "elogin" mentioned in it.

**Comment by amano-kenji** [comment] 2022-12-01 12:26
Yet, reality slapped me with the error message that /lib64/elogind/elogind-uaccess-command didn't exist in initramfs.

**Comment by johannbg** [comment] 2022-12-21 18:53
Looks like a downstream issue hence closing

**Closed by johannbg** 2022-12-21 18:53 UTC
Labels: bug, gentoo

**Comment by amano-kenji** [comment] 2022-12-22 08:34
I think 70-uaccess.rules is designed to trigger execution of /lib64/elogind/elogind-uaccess-command. This isn't an issue, but a design decision by logind.
