### ISSUE TITLE
TEST-21-NFS-NM failing

### ISSUE THREAD

**Issue by pvalena** [dracutdevs/dracut#1857] opened 2022-06-28 15:23 UTC
**Describe the bug**
Fedora NFS issues in the CI:
  https://github.com/dracutdevs/dracut/runs/7071776979?check_suite_focus=true
  https://github.com/dracutdevs/dracut/runs/7071776822?check_suite_focus=true

```
CLIENT TEST END: NFSv3 root=dhcp DHCP path only [FAILED - BAD EXIT]
TEST: root filesystem on NFS with network-manager   [FAILED] 
see /__w/dracut/dracut/test/TEST-20-NFS/test-TEST-21.log
make[2]: *** [../Makefile.testdir:5: all] Error 1
make[1]: Leaving directory '/__w/dracut/dracut/test/TEST-21-NFS-NM'
```

**Distribution used**
fedora:latest
Probably reported also as: https://bugzilla.redhat.com/show_bug.cgi?id=2100741 ?

**Dracut version**
057 (actually fails in CI commit https://github.com/dracutdevs/dracut/commit/7fa0094c0087a827a22f30ec62f03f243b000bf3)

**Additional context**
https://github.com/dracutdevs/dracut/pull/1856

**Comment by aafeijoo-suse** [comment] 2022-06-29 06:15
Yes, we also had this (https://bugzilla.suse.com/show_bug.cgi?id=1200710#c14), but it's caused by a downstream patch in `nfs-utils` that will be fixed, so I don't think we need to do anything upstream for now.

**Comment by liutgnu** [comment] 2022-07-04 02:25
I think this issue is fixed in nfs-utils-2-6-2-rc8, patch [1] has already merged.

[1] http://git.linux-nfs.org/?p=steved/nfs-utils.git;a=commit;h=5e60e38aa4ba251ef66610514be5f45c41519e0f

**Comment by LaszloGombos** [comment] 2022-08-16 16:06
No longer seem to fail - https://github.com/dracutdevs/dracut/runs/7844035450?check_suite_focus=true

Perhaps this issue can be closed now.

**Closed** 2022-10-25 01:57 UTC
Labels: bug
